server:
  port: 8081
dubbo:
  application:
    name: provider
  registry:
    #multicast://224.5.6.7:1234
    address: zookeeper://127.0.0.1:2181
    timeout: 6000
  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: com.xxxx.provider.service